### ISSUE TITLE
ExampleJob undefined after executing it in Meteor.startup()

### ISSUE THREAD

**Issue by CdavM** [peerlibrary/meteor-classy-job#4]
After running in Meteor.startup():

```
class ExampleJob extends Job {
  run() {
    this.logInfo("Hello world from: " + this.data.name);
  }
}

ExampleJob.register();
```

I cannot register any jobs in subsequent methods due to `ReferenceError: ExampleJob is not defined`

I also can't find it in the scope of `meteor shell`

However, it works fine if I declare the classes from within meteor shell.

Where should I declare new jobs? Any reasons Meteor.startup is not registering them properly?

**Comment by mitar** [comment]
What do you mean? This has nothing with this package. This is a question how Meteor exports its symbols. You created a local class with name `ExampleJob` so it is available only inside that JavaScript module (file). You can export it (read ES2016 documentation on that), and import it elsewhere. Or you can use Meteor's packages to make this symbol exported from the old-style Meteor packages.

So this all ends up being a question how you manage your symbols in your app.

[Read here more](https://docs.meteor.com/packages/modules.html).

`register` just stores it internally so that worker knows how to resolve them.

**Comment by mitar** [comment]
You could probably misuses `Job.types.ExampleJob` to get access to this registry of registered jobs, but you should probably not do that. :-)
