### ISSUE TITLE
Setting infinite number of worker instances

### ISSUE THREAD

**Issue by janat08** [peerlibrary/meteor-classy-job#5]
Would setting ridiculous number of worker instances would be okay? Hopefully it won't actually go about creating that many workers on a single node.js.

**Comment by mitar** [comment]
You spawn number of workers. You just pass this argument to tell how many of workers there are, so that for regular intervals can be nicely spread across multiple workers. For example, if you want this package to check if any new job is ready every 10 seconds, if you have 10 workers, then you want each of those workers to check every 100 seconds. Now, if you set number of workers to infinite, then code will multiply 10 seconds with infinity, and will check if jobs are ready never. Probably not what you want.

**Comment by janat08** [comment]
Wouldn't it observer for new jobs instead, may I set one if there's dynamic number of nodes?

**Comment by mitar** [comment]
I do not understand what you wrote above. Check the code and see how this parameter is being used.

**Comment by janat08** [comment]
It would be cool if there was a job that polls for a number of workers, by not "completing" and not being done twice by the same server, and is reponsible for checking against delayed and failed in case that you have server that autoscales or is running in dockers that are susceptible to destruction.

**Comment by mitar** [comment]
Yes, that would be a nice feature to have, to support dynamically scaling of number of workers. For now, you can just be conservative and scale it and leave worker number fixed at a minimum number of those. It just means your queue will be checked more often than your interval if you have in fact more workers.
